#!/usr/bin/env python3
"""
Clustered-only denominator sensitivity analysis for the GeNeDis 2026 GBM paper.

Uses the SAME primary-label axis memberships as the main analysis.
No embeddings, UMAP, HDBSCAN, or BERTopic are rerun.

Primary denominator:
    axis topic publications / all eligible GBM publications

Sensitivity denominator:
    axis topic publications / clustered GBM publications only

Required inputs:
  1) primary_axis_membership.csv
     (generated by axis_definition_sensitivity.py)
  2) topic_prevalence_by_year.csv
     (generated by run_bertopic_candidate_b.py)

Expected prevalence columns:
  publication_year
  topic
  topic_documents
  all_gbm_documents
  clustered_documents

Outputs:
  denominator_sensitivity_annual.csv
  denominator_sensitivity_stats.csv
  denominator_sensitivity_comparison.csv
  denominator_sensitivity_results.txt
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr


AXIS_ORDER = [
    "Hypoxia / angiogenesis",
    "Metabolism / stress",
    "Immune / tumor microenvironment",
    "Treatment resistance",
]


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--membership", type=Path, required=True)
    p.add_argument("--prevalence", type=Path, required=True)
    p.add_argument(
        "--output-dir",
        type=Path,
        default=Path("clustered_denominator_sensitivity"),
    )
    p.add_argument("--start-year", type=int, default=2011)
    p.add_argument("--end-year", type=int, default=2025)
    return p.parse_args()


def bh_fdr(p_values):
    p = np.asarray(p_values, dtype=float)
    n = len(p)

    order = np.argsort(p)
    ranked = p[order]

    adjusted = ranked * n / np.arange(1, n + 1)
    adjusted = np.minimum.accumulate(adjusted[::-1])[::-1]
    adjusted = np.minimum(adjusted, 1.0)

    out = np.empty(n, dtype=float)
    out[order] = adjusted
    return out


def direction(rho, q):
    if q < 0.05 and rho > 0:
        return "significant increase"
    if q < 0.05 and rho < 0:
        return "significant decrease"
    if rho > 0:
        return "positive, non-significant"
    if rho < 0:
        return "negative, non-significant"
    return "no monotonic trend"


def main():
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    membership = pd.read_csv(args.membership)
    prevalence = pd.read_csv(args.prevalence)

    required_membership = {"topic", "axis"}
    missing = required_membership - set(membership.columns)
    if missing:
        raise ValueError(
            f"Missing membership columns: {sorted(missing)}"
        )

    required_prevalence = {
        "publication_year",
        "topic",
        "topic_documents",
        "all_gbm_documents",
        "clustered_documents",
    }
    missing = required_prevalence - set(prevalence.columns)
    if missing:
        raise ValueError(
            f"Missing prevalence columns: {sorted(missing)}"
        )

    membership = membership.copy()
    prevalence = prevalence.copy()

    membership["topic"] = pd.to_numeric(
        membership["topic"], errors="raise"
    ).astype(int)

    prevalence["topic"] = pd.to_numeric(
        prevalence["topic"], errors="raise"
    ).astype(int)

    prevalence["publication_year"] = pd.to_numeric(
        prevalence["publication_year"], errors="raise"
    ).astype(int)

    for col in [
        "topic_documents",
        "all_gbm_documents",
        "clustered_documents",
    ]:
        prevalence[col] = pd.to_numeric(
            prevalence[col], errors="raise"
        )

    prevalence = prevalence[
        prevalence["publication_year"].between(
            args.start_year, args.end_year
        )
    ].copy()

    # One denominator pair per year.
    denominators = (
        prevalence[
            [
                "publication_year",
                "all_gbm_documents",
                "clustered_documents",
            ]
        ]
        .drop_duplicates()
        .sort_values("publication_year")
    )

    counts_per_year = (
        denominators.groupby("publication_year")
        .size()
    )
    if not (counts_per_year == 1).all():
        raise ValueError(
            "More than one denominator pair found for at least one year."
        )

    expected_years = list(range(args.start_year, args.end_year + 1))
    observed_years = denominators["publication_year"].tolist()

    if observed_years != expected_years:
        raise ValueError(
            f"Expected years {expected_years}, got {observed_years}"
        )

    annual_rows = []

    for axis in AXIS_ORDER:
        topic_ids = (
            membership.loc[membership["axis"] == axis, "topic"]
            .drop_duplicates()
            .astype(int)
            .tolist()
        )

        if not topic_ids:
            raise ValueError(f"No topics found for axis: {axis}")

        tmp = prevalence[
            prevalence["topic"].isin(topic_ids)
        ].copy()

        axis_counts = (
            tmp.groupby("publication_year", as_index=False)[
                "topic_documents"
            ]
            .sum()
            .rename(
                columns={"topic_documents": "axis_topic_documents"}
            )
        )

        annual = (
            denominators
            .merge(
                axis_counts,
                on="publication_year",
                how="left",
                validate="one_to_one",
            )
            .sort_values("publication_year")
        )

        annual["axis_topic_documents"] = (
            annual["axis_topic_documents"].fillna(0)
        )

        annual["prevalence_all_gbm_percent"] = (
            100.0
            * annual["axis_topic_documents"]
            / annual["all_gbm_documents"]
        )

        annual["prevalence_clustered_only_percent"] = (
            100.0
            * annual["axis_topic_documents"]
            / annual["clustered_documents"]
        )

        annual["axis"] = axis
        annual["n_axis_topics"] = len(topic_ids)

        annual_rows.append(annual)

    annual_all = pd.concat(annual_rows, ignore_index=True)

    annual_all.to_csv(
        args.output_dir / "denominator_sensitivity_annual.csv",
        index=False,
    )

    stats_rows = []

    for axis in AXIS_ORDER:
        g = (
            annual_all[annual_all["axis"] == axis]
            .sort_values("publication_year")
        )

        rho_all, p_all = spearmanr(
            g["publication_year"],
            g["prevalence_all_gbm_percent"],
        )

        rho_clustered, p_clustered = spearmanr(
            g["publication_year"],
            g["prevalence_clustered_only_percent"],
        )

        stats_rows.append(
            {
                "axis": axis,
                "n_axis_topics": int(g["n_axis_topics"].iloc[0]),
                "n_years": len(g),

                "all_gbm_start_percent": float(
                    g.iloc[0]["prevalence_all_gbm_percent"]
                ),
                "all_gbm_end_percent": float(
                    g.iloc[-1]["prevalence_all_gbm_percent"]
                ),
                "all_gbm_rho": float(rho_all),
                "all_gbm_p": float(p_all),

                "clustered_start_percent": float(
                    g.iloc[0]["prevalence_clustered_only_percent"]
                ),
                "clustered_end_percent": float(
                    g.iloc[-1]["prevalence_clustered_only_percent"]
                ),
                "clustered_rho": float(rho_clustered),
                "clustered_p": float(p_clustered),
            }
        )

    stats = pd.DataFrame(stats_rows)

    stats["all_gbm_q_bh"] = bh_fdr(
        stats["all_gbm_p"].to_numpy()
    )

    stats["clustered_q_bh"] = bh_fdr(
        stats["clustered_p"].to_numpy()
    )

    stats["all_gbm_interpretation"] = [
        direction(r, q)
        for r, q in zip(
            stats["all_gbm_rho"],
            stats["all_gbm_q_bh"],
        )
    ]

    stats["clustered_interpretation"] = [
        direction(r, q)
        for r, q in zip(
            stats["clustered_rho"],
            stats["clustered_q_bh"],
        )
    ]

    stats["same_rho_sign"] = (
        np.sign(stats["all_gbm_rho"])
        == np.sign(stats["clustered_rho"])
    )

    stats["same_significance_status"] = (
        (stats["all_gbm_q_bh"] < 0.05)
        == (stats["clustered_q_bh"] < 0.05)
    )

    stats["robust_direction_and_significance"] = (
        stats["same_rho_sign"]
        & stats["same_significance_status"]
    )

    stats.to_csv(
        args.output_dir / "denominator_sensitivity_stats.csv",
        index=False,
    )

    comparison_cols = [
        "axis",
        "n_axis_topics",
        "all_gbm_rho",
        "all_gbm_q_bh",
        "all_gbm_interpretation",
        "clustered_rho",
        "clustered_q_bh",
        "clustered_interpretation",
        "same_rho_sign",
        "same_significance_status",
        "robust_direction_and_significance",
    ]

    comparison = stats[comparison_cols].copy()

    comparison.to_csv(
        args.output_dir / "denominator_sensitivity_comparison.csv",
        index=False,
    )

    lines = []
    lines.append("CLUSTERED-ONLY DENOMINATOR SENSITIVITY")
    lines.append("=" * 39)

    for row in stats.itertuples(index=False):
        lines.append("")
        lines.append(row.axis)
        lines.append(
            f"  All-GBM denominator: "
            f"{row.all_gbm_start_percent:.4f}% -> "
            f"{row.all_gbm_end_percent:.4f}%; "
            f"rho={row.all_gbm_rho:.4f}; "
            f"p={row.all_gbm_p:.6g}; "
            f"BH q={row.all_gbm_q_bh:.6g}; "
            f"{row.all_gbm_interpretation}"
        )
        lines.append(
            f"  Clustered-only denominator: "
            f"{row.clustered_start_percent:.4f}% -> "
            f"{row.clustered_end_percent:.4f}%; "
            f"rho={row.clustered_rho:.4f}; "
            f"p={row.clustered_p:.6g}; "
            f"BH q={row.clustered_q_bh:.6g}; "
            f"{row.clustered_interpretation}"
        )
        lines.append(
            f"  Same sign: {row.same_rho_sign}; "
            f"same significance status: "
            f"{row.same_significance_status}"
        )

    all_same_sign = bool(stats["same_rho_sign"].all())
    all_same_status = bool(
        stats["same_significance_status"].all()
    )

    lines.append("")
    lines.append("OVERALL")
    lines.append("=======")
    lines.append(
        f"All four axes preserve trend direction: {all_same_sign}"
    )
    lines.append(
        "All four axes preserve significance/non-significance "
        f"status: {all_same_status}"
    )

    if all_same_sign and all_same_status:
        lines.append(
            "Suggested manuscript sentence: "
            "\"Temporal directions and inferential interpretations "
            "were unchanged when prevalence was normalized to "
            "clustered publications only.\""
        )
    elif all_same_sign:
        lines.append(
            "Suggested manuscript sentence: "
            "\"Temporal directions were unchanged when prevalence "
            "was normalized to clustered publications only, although "
            "the statistical significance of at least one axis differed.\""
        )
    else:
        lines.append(
            "At least one axis changed trend direction under the "
            "clustered-only denominator. Report denominator "
            "sensitivity explicitly rather than claiming robustness."
        )

    result_path = (
        args.output_dir / "denominator_sensitivity_results.txt"
    )
    result_path.write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )

    print("\n=== CLUSTERED-ONLY DENOMINATOR SENSITIVITY ===")
    print(
        comparison.to_string(
            index=False,
            float_format=lambda x: f"{x:.4f}",
        )
    )
    print("")
    print(f"Outputs: {args.output_dir}")
    print("")
    print("\n".join(lines[-8:]))


if __name__ == "__main__":
    main()
